# Generated by Django 4.2.1 on 2023-06-13 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_authtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.AlterField(
            model_name='authtoken',
            name='expiresIn',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
