# Generated by Django 4.2.1 on 2023-06-25 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_comment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='expiresIn',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
